# Languages
#   Create a section for each of your site's languages.
#   Documentation: https://docs.hugoblox.com/reference/language/

# Default language
en:
  locale: en-us

zh:
  locale: zh-Hans
  contentDir: content/zh
  title: Yakun Liu
  params:
    description: Yakun Liu's Chinese academic portfolio and CV.
