# Navigation Links

main:
  - name: About
    url: /#about
    weight: 10
  - name: Interests
    url: /#interests
    weight: 20
  - name: Publications
    url: /#publications
    weight: 30
  - name: Projects
    url: /#projects
    weight: 40
  - name: Skills
    url: /#skills
    weight: 50
